- hosts: httpd
  name: "web server conf"
  tasks:
   - package:
       name: httpd
       state: present
     when:  ansible_os_family == "RedHat"
   - template:
       src: /root/templates/web.conf.j2
       dest: /etc/www/conf.d/web.conf.j2
       owner: apache
       mode: 0644
     when:  ansible_os_family == "RedHat"
   - copy:
       src: /var/www/html/index.html
       dest: /var/www/anurag
       owner: apache
       mode: 0644
     when:  ansible_os_family == "RedHat"
   - service:
       name: httpd
       state: started
       enabled: yes
     when:  ansible_os_family == "RedHat"
   - firewalld:
       service: http
       permanent: true
       state: enabled
       immediate: true
     when:  ansible_os_family == "RedHat"




